### ISSUE TITLE
Are you sure next-translate-plugin should be a dev dependency?

### ISSUE THREAD

**Issue by brunoscopelliti** [aralroca/next-translate-plugin#65]
**What version of this package are you using?**

```
next: 13.4.11
next-translate: 2.5.2
next-translate-plugin: 2.5.2
```

**What operating system, Node.js, and npm version?**

Docker image

```
node:18.15.0-alpine3.17
```

**What happened?**

After building next.js project I delete the dev dependencies, and start the project.
When I start the project i get this error:

```
Error: Cannot find module 'next-translate-plugin'
Require stack:
- /app/next.config.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
at /app/node_modules/next/dist/server/require-hook.js:113:36
at Module._load (node:internal/modules/cjs/loader:920:27)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/app/next.config.js:1:23)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [ '/app/next.config.js' ]
}
Node.js v18.15.0
Container called exit(1).
```

I fixed the problem, installing `next-translate-plugin` as a normal dependency, but this surprised me a bit cause in the readme it is stated that `next-translate-plugin` is a dev dependency.

**What did you expect to happen?**

I didn't expect to have to keep `next-translate-plugin` around after building the project.

**Comment by aralroca** [comment]
It is curious because it only runs during build, not in runtime. But well, put it in dependencies for now and I will investigate why it happens, because it shouldn't be necessary. Thanks @brunoscopelliti  to report it

**Comment by StLyn4** [comment]
If I understand correctly, when the production server starts, it loads `next.config.js`. the `webpack` function is not executed, but the module is required at the beginning of the file anyway. So, in theory, all next.js plugins should be declared in `dependencies`

**Comment by Tronder** [comment]
We also ended in the devDependency trap, maybe someone could update this error message when running the app without next-translate-plugin installed:
![image](https://github.com/user-attachments/assets/b341923e-60c7-4227-a20b-94fa7c7903f8)
